blueprints/manage_bp.py
from flask import Blueprint,render_template,g
from flask import Flask, jsonify,request,flash
from flask import session
from database import  insert_scorerecord,get_alluser
from permission import Permissions,permission_required
import pypinyin

bp = Blueprint("manage",__name__,url_prefix="/manage")

@bp.route("/insertscore", methods=['post','get'])
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def insertscore():
    if request.method=='POST':
        userid = request.form['userid'] 
        score_1 = request.form['score_1'] 
        score_2 = request.form['score_2'] 
        score_3 = request.form['score_3'] 
        insert_scorerecord(userid,score_1,score_2,score_3,3)
        return jsonify({'update':'ok'})
    else:
        users = get_alluser()
        userlist = []
        for item in users:
            namepylist = pypinyin.pinyin ( item.username, style=pypinyin.FIRST_LETTER)
            namepy = ''.join(i[0] for i in namepylist)
            userlist.append({'userid':item.userid,'name':item.username,'py':namepy})
        return render_template("add_score.html",userlist=userlist)
    
@bp.route('/userlist',methods=['GET', 'POST'])
@permission_required(Permissions.USER_PERMISSION)
def userlist():
    if(request.method == 'GET'):
        return render_template("userlist.html")
    
@bp.route('/userlistdata',methods=['GET', 'POST'])
@permission_required(Permissions.USER_PERMISSION)
def userlistdata():
    users = get_alluser()
    userlist = []
    for item in users:
        namepylist = pypinyin.pinyin ( item.username, style=pypinyin.FIRST_LETTER)
        namepy = ''.join(i[0] for i in namepylist)
        userlist.append({'userid':item.userid,'workid':item.workid,'name':item.username,'py':namepy})
    return jsonify(userlist)

blueprints/paper_bp.py
from flask import Blueprint,render_template,g
from flask import Flask, jsonify,request,flash
from flask import session
from database import  get_paper_byid, insert_paper,get_user_answerrecord,paper_hasanswer,\
    get_paper_questions_byid, insert_record,get_all_paper_filterbystate,get_alluser,get_alldepartment,drop_paper,insert_scorerecord,\
    get_all_paper_filterbystate_user,unlockpaper,get_answerrecord_bypaper
from permission import Permissions,permission_required
import pypinyin

bp = Blueprint("paper",__name__,url_prefix="/paper")
@bp.route('/list',methods=['GET'])
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def showPaperList():
    return render_template('paperlist.html')
    '''elif request.method=='POST':
        data = []
        paperlist = get_all_paper()
        for paper in paperlist:
            p={}
            p['paperid']=paper.paperid
            p['paper_title']=paper.paper_title
            p['ownerid']=paper.ownerid
            p['createtime']=paper.createtime
            p['modifytime']=paper.modifytime
            p['question_count']=paper.question_count
            data.append(p)
        tabele_data  = {'total': 1,'rows':data}
        return jsonify(tabele_data)'''


@bp.route('/paperdata/state=<statelist>',methods=['GET'])
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def paperData(statelist):
    data = []
    paperlist = get_all_paper_filterbystate_user(statelist.split(','),session.get('nl_user_id'))
    idx = 0
    for paper in paperlist:
        idx = idx+1
        p={}
        p['index']=idx
        p['paperid']=paper.paperid
        p['paper_title']=paper.paper_title
        p['ownerid']=paper.ownerid
        p['createtime']=paper.createdate.strftime("%Y-%m-%d %H:%M:%S")
        if(paper.modifydate is not None):
            p['modifytime']=paper.modifydate.strftime("%Y-%m-%d %H:%M:%S")
        else:
            p['modifytime']=''
        p['question_count']=paper.quetion_count
        if(paper.state =='1'):
            p['ispublish']="已发布"
        else:
            p['ispublish']="未发布"
        p['question_count']=paper.quetion_count
        p['hasanaser'] = paper_hasanswer(session.get('nl_user_id'),paper.paperid)
        data.append(p)
    table_data  = {'total': 1,'rows':data}
    return jsonify(table_data)


def getusersanddepars():
    users = get_alluser()
    userlist = []
    for item in users:
        namepylist = pypinyin.pinyin ( item.username, style=pypinyin.FIRST_LETTER)
        namepy = ''.join(i[0] for i in namepylist)
        userlist.append({'userid':item.userid,'name':item.username,'py':namepy})
    departments = get_alldepartment()
    departmentlist = []
    for item in departments:
        departnamelist = pypinyin.pinyin ( item.departmentname, style=pypinyin.FIRST_LETTER)
        departpy = ''.join(i[0] for i in departnamelist)
        departmentlist.append({'departmentid':item.departmentid,'name':item.departmentname,'py':departpy})
    return userlist,departmentlist


@bp.route('/create_paper', methods=['GET', 'POST'])
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def createPaper():
    if request.method=='GET':
        userlist,departmentlist=getusersanddepars()
        return render_template('create_paper.html',userlist=userlist,departmentlist= departmentlist)
    elif request.method=='POST':
        all_data = request.form.getlist('all_data[]')    #试卷上所有题目 返回的格式是一道题目一个列表项，题目中以|分隔，依次为
                                                         #题目、是否选择A(1是选择了，0是没选择)、选项A内容........
        paper_title = request.form['paper_title']    #试卷标题
        paper_owner = request.form['paper_owner']    #0:所有人   1:个人的
        paper_id = request.form['paper_id'] 
        quetion_count = request.form['quetion_count']
        state = request.form['state']
        hostid = request.form['hostid']
        departid = request.form['departid']
        #if(paper_owner=='1' and g.user is not None):
        insert_paper(paper_title,paper_id,quetion_count,state,session.get('nl_user_id'),all_data,int(hostid),departid)
        
        return jsonify("refresh") 



@bp.route('/edit_paper')
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def editPaper():
    paper_id = request.args.get("paper_id")
    papers = []
    paper_qustions = get_paper_questions_byid(paper_id)
    paper_info = get_paper_byid(paper_id)
    p={}
    p['paper_title']=paper_info[0].paper_title
    p['paper_id']=paper_info[0].paperid
    p['ownerid']=paper_info[0].ownerid
    p['hostid']=paper_info[0].hostid
    p['departid']=paper_info[0].departmentid
    papers.append(p)
    for question in paper_qustions:
        p={}
        p['questionid']=question.questionid
        p['paperid']=question.paperid
        p['detail']=question.detail
        p['type']=question.type
        p['mark']=question.mark
        papers.append(p)
    flash(papers)
    userlist,departmentlist=getusersanddepars()
    return render_template('create_paper.html',userlist=userlist,departmentlist= departmentlist)
    


@bp.route('/answer')
@permission_required(Permissions.USER_PERMISSION)
def answer():
    paper_id = request.args.get("paper_id")
    if(paper_hasanswer(session.get('nl_user_id'),paper_id) != -1):
        return render_template('answerpaperlist.html')
    papers = []
    paper_qustions = get_paper_questions_byid(paper_id)
    paper_info = get_paper_byid(paper_id)
    p={}
    p['paper_title']=paper_info[0].paper_title
    p['paper_id']=paper_info[0].paperid
    p['ownerid']=paper_info[0].ownerid
    
    papers.append(p)
    for question in paper_qustions:
        p={}
        p['questionid']=question.questionid
        p['paperid']=question.paperid
        p['detail']=question.detail
        p['type']=question.type
        p['mark']=question.mark
        papers.append(p)
    flash(papers)
    insert_record(paper_id,session.get('nl_user_id'),0,0)
    return render_template('answer_paper.html')



@bp.route('/write_result', methods=['GET', 'POST'])
@permission_required(Permissions.USER_PERMISSION)
def get_result():
    paper_id = request.form['paper_id'] 
    correct_count = request.form['correct_count'] 
    userid = session.get('nl_user_id') 
    recordid = insert_record(paper_id,session.get('nl_user_id'),1,correct_count)
    return render_template('answerpaperlist.html')



@bp.route('/deletepaper', methods=['GET', 'POST'])
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def deletepaper():
    paper_id = request.form['paper_id']
    drop_paper(paper_id)
    return render_template('paperlist.html')

@bp.route('/unlockpaper', methods=['GET', 'POST'])
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def unlockuserpaper():
    if request.method=='GET':
        data=[]
        paperlist = get_all_paper_filterbystate([0,1])
        for paper in paperlist:
            p={}
            p['paperid']=paper.paperid
            p['paper_title']=paper.paper_title
            titlepylist = pypinyin.pinyin (paper.paper_title, style=pypinyin.FIRST_LETTER)
            titlepy = ''.join(i[0] for i in titlepylist)
            p['py']=titlepy
            data.append(p)
        return render_template('lockpaperlist.html',data=data)
    elif request.method=='POST':
        answerid = request.form['answerid']
        unlockpaper(answerid)
        return render_template('paperlist.html')

@bp.route('/lockuserdata', methods=['GET','POST'])
@permission_required(Permissions.MANAGEMENT_PERMISSION)
def lockuserdata():
    paper_id = request.args.get("paper_id")
    answerrecord = get_answerrecord_bypaper(paper_id)
    data = []
    for record in answerrecord:
        p={}
        p['answerid']=record[0].recordid
        p['workid']=record[1].workid
        p['username']=record[1].username
        p['insertdate']=record[0].insertdate.strftime("%Y-%m-%d %H:%M:%S")
        data.append(p)
    return jsonify(data)

@bp.route('/answerpaperlist')
@permission_required(Permissions.USER_PERMISSION)
def showanserpaperlist():
    return render_template('answerpaperlist.html')
    '''elif request.method=='POST':
        data = []
        paperlist = get_all_paper()
        for paper in paperlist:
            p={}
            p['paperid']=paper.paperid
            p['paper_title']=paper.paper_title
            p['ownerid']=paper.ownerid
            p['createtime']=paper.createtime
            p['modifytime']=paper.modifytime
            p['question_count']=paper.question_count
            data.append(p)
        tabele_data  = {'total': 1,'rows':data}
        return jsonify(tabele_data)'''
        

blueprints/users_bp.py
from flask import Blueprint,render_template,g,flash,jsonify,request,session,redirect
from database import get_user_scores,get_user_answerrecord,get_paper_byid,get_user_bysession,get_user_readrecord,\
    get_article_byid,alterpassword
from permission import Permissions,permission_required
bp = Blueprint("users_bp",__name__,url_prefix="/user")

@bp.route("/home")
@permission_required(Permissions.USER_PERMISSION)
def showusercenter():
    user_info = []
    if hasattr(g,'user') and g.user is not None:
        userscore = list(get_user_scores(g.user.userid)[0])
        #answerrecord = get_user_answerrecord(g.user.userid)
        current_user = get_user_bysession()
        info = {}
        info['userscore'] = userscore
        info['username'] = current_user.username
        user_info.append(info)
        # for item in answerrecord:
        #     info = {}
        #     info['paperid'] = item[0].paperid
        #     info['insertdate'] = item[0].insertdate.strftime('%Y-%m-%d %H:%M:%S')
        #     user_info.append(info)
        flash(user_info)
    return render_template("usercenter.html")


@bp.route("/alterpassword",methods=['GET', 'POST'])
@permission_required(Permissions.USER_PERMISSION)
def alteruserpassword():
    if request.method == 'GET':
        return render_template("alterpassword.html")
    elif request.method == 'POST':
        repeatnewpass = request.form.get('repeatnewpass')
        newpass = request.form.get('newpass')
        flag = alterpassword(session.get('nl_user_id'),newpass)
        return redirect('/loginout')

@bp.route('/answerdata',methods=['GET', 'POST'])
@permission_required(Permissions.USER_PERMISSION)
def answerdata():
    user_info = []
    if hasattr(g,'user') and g.user is not None:
        answerrecord = get_user_answerrecord(g.user.userid)
        info = {}
        idx = 0
        for item in answerrecord:
            paper_info = get_paper_byid(item[0].paperid)
            idx = idx+1
            info = {}
            info['index'] = idx
            info['papername'] = paper_info[0].paper_title
            info['score'] = item[0].getmark
            info['insertdate'] = item[0].insertdate.strftime('%Y-%m-%d %H:%M:%S')
            if(item[1] is not None):
                info['score_1'] = item[1].score_1
                info['score_2'] = item[1].score_2
                info['score_3'] = item[1].score_3
            user_info.append(info)
    table_data  = {'total': 2,'rows':user_info}
    return jsonify(table_data)

@bp.route('/readdata',methods=['GET', 'POST'])
@permission_required(Permissions.USER_PERMISSION)
def readdata():
    user_info = []
    if hasattr(g,'user') and g.user is not None:
        readrecord = get_user_readrecord(g.user.userid)
        info = {}
        idx = 0
        for item in readrecord:
            article_info = get_article_byid(item[0].articleid)
            idx = idx+1
            info = {}
            info['index'] = idx
            info['title'] = article_info[0][0].title
            info['insertdate'] = item[0].insertdate.strftime('%Y-%m-%d %H:%M:%S')
            if(item[1] is not None):
                info['score_1'] = item[1].score_1
                info['score_2'] = item[1].score_2
                info['score_3'] = item[1].score_3
            user_info.append(info)
    table_data  = {'total': 2,'rows':user_info}
    return jsonify(table_data)



templates/add_score.html
{%extends "createcenter.html"%}
{% block body %}
<script src="{{url_for('static',filename = 'bootstrap-input-spinner-master/src/bootstrap-input-spinner.js')}}"></script>
<script src="{{url_for('static',filename = 'bootstrap-select/js/bootstrap-select.js')}}"></script>
<link rel="stylesheet" href="{{url_for('static',filename = 'bootstrap-select/css/bootstrap-select.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename = 'mystyle/mystyle.css')}}">


<div class="scorescontainer">
    <span class="scorespan">一类积分</span>
    <input id="singlemark1" class="mark" type="number" min="0" max="100" placeholder="一类积分"/>
    <span class="scorespan">二类积分</span>
    <input id="singlemark2" class="mark" type="number" min="0" max="100" placeholder="二类积分"/>
    <span class="scorespan">学分</span>
    <input id="singlemark3" class="mark" type="number" min="0" max="100" placeholder="学分"/>
    <select class="selectpicker show-tick" data-live-search="true" id="userdroplist" title="选择用户" data-hide-disabled="true"></select>
    <div class="d-grid gap-2">
        <button id="addbtn" class="btn btn-primary" type="button">提交</button>
    </div>
</div>


<script type=text/javascript>
    $("input[type='number']").inputSpinner()
    var $userdroplist = document.getElementById('userdroplist')
    var userlist = {{userlist|tojson}}
    //$departdroplist.innerHTML = $departdroplist.innerHTML+("<option data-content='<span class=text>safasdfas</span>'></option>")
    function appenduserlistnode(item,index)
    {
        $userdroplist.innerHTML = $userdroplist.innerHTML+
        ("<option value="+item['userid']+" data-tokens="+item['py']+" data-content='<span color=black>"+item['name']+"</span>'></option>")
    }
    userlist.forEach(appenduserlistnode)
    $('#addbtn').bind('click', function() {
        $.ajax({
        type: "post",
        url: '/manage/insertscore',
        async : false,
        data: {'userid':$userdroplist.options[$userdroplist.selectedIndex].value,'score_1':$('#singlemark1').val(),'score_2':$('#singlemark2').val(),'score_3':$('#singlemark3').val()},
        success: function () {
            alert('添加成功')
        }
        }); 
    });
</script>
{% endblock %}

templates/answerpaperlist.html
{%extends "base.html"%}
{% block body %}

<!--data-url="https://examples.wenzhixin.net.cn/examples/bootstrap_table/data"-->
<div class="mylistcontainer">
<table id="table" class="phoneanswertable"  data-toolbar="#toolbar" data-search="true" data-show-refresh="true" 
  data-show-columns-toggle-all="true" data-click-to-select="true" data-minimum-count-columns="2" 
  data-id-field="paperid" data-side-pagination="client" data-page-size = '6' data-pagination='true' data-response-handler="responseHandler" >
</table>
</div>

<script type=text/javascript>

  $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
  var $table = $('#table')
  var $remove = $('#remove')
  var $add = $('#add')
  var selections = []

  function getIdSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {
      return row.id
    })
  }

  function responseHandler(res) {
    $.each(res.rows, function (i, row) {
      row.state = $.inArray(row.id, selections) !== -1
    })
    return res
  }

  function operateFormatter(value, row, index) {
    if(value == -1)
    {
        return [
        '<a class="like" href="javascript:void(0)" title="答题">',
        '<i class="fa fa-arrow-circle-right fa-xl" aria-hidden="true"></i>',
        '</a>'].join('')
    }
    else
    {
      return [
        '<span>'+value+'</span'].join('')
    }
    
  }


  window.operateEvents = {
    'click .like': function (e, value, row, index) {
      //alert(row['paperid']+'  You click like action, row: ' + JSON.stringify(row))
      window.location.href = $SCRIPT_ROOT+'/paper/answer?paper_id='+row['paperid']
    },
    'click .remove': function (e, value, row, index) {
      alert(row.paperid)
      $table.bootstrapTable('remove', {
        field: 'paperid',
        values: [row.paperid]
      })
      $.ajax({
        type: "POST",
        url: $SCRIPT_ROOT+'/paper/deletepaper',
        async : false,
        data: {'paper_id':row.paperid},
        success: function () {
            //window.location.href = $SCRIPT_ROOT+'/paper/list'
            initTable()
        }
    });
    }
  }

  function initTable() {
    $table.bootstrapTable('destroy').bootstrapTable({
      url:$SCRIPT_ROOT+ '/paper/paperdata/state=1',
      dataType: "json",
      
      locale: "zh-CN",
      columns: [
        [{
          title: '序号',
          rowspan: 2,
          field: 'index',
          align: 'center',
          sortable: true,
          valign: 'middle',
          visible: false,
        },{
          title: '试卷序号',
          field: 'paperid',
          rowspan: 2,
          align: 'center',
          valign: 'middle',
          sortable: true,
          visible: false,
          width:10
        }, {
          title: '答题列表',
          colspan: 6,
          align: 'center'
        }],
        [{
          field: 'paper_title',
          title: '试卷名称',
          sortable: true,
          align: 'center'
        }, {
          field: 'ownerid',
          title: '创建者',
          sortable: true,
          align: 'center',
          visible: false,
        }, {
          field: 'question_count',
          title: '题目数量',
          sortable: true,
          align: 'center',
          visible: false,
        },{
          field: 'createtime',
          title: '创建时间',
          sortable: true,
          align: 'center',
          visible: false,
        },{
          field: 'modifytime',
          title: '修改时间',
          sortable: true,
          align: 'center',
          visible: false,
        },{
          field: 'hasanaser',
          title: '操作',
          align: 'center',
          clickToSelect: false,
          events: window.operateEvents,
          formatter: operateFormatter
        }]
      ]
    })
    $table.on('check.bs.table uncheck.bs.table ' +
      'check-all.bs.table uncheck-all.bs.table',
    function () {
      $remove.prop('disabled', !$table.bootstrapTable('getSelections').length)

      // save your data, here just save the current page
      selections = getIdSelections()
      // push or splice the selections if you want to save all data selections
    })
    //$table.on('all.bs.table', function (e, name, args) {
      //console.log(name, args)
    //})
    $remove.click(function () {
      var ids = getIdSelections()
      $table.bootstrapTable('remove', {
        field: 'paperid',
        values: ids
      })
      $remove.prop('disabled', true)
    })

    $add.click(function () {
      window.location.href = $SCRIPT_ROOT+'/paper/create_paper'
    })
  }
  $(function() {
    initTable()
    //$('#locale').change(initTable)
    $(window).resize(function () {
      $('#table').bootstrapTable('resetView');
  });
  })
</script>
{% endblock %}

templates/bootstrap_login.html
{%extends "base.html"%}
{% block body %}
    
    <link rel="stylesheet" href="{{url_for('static',filename = 'mystyle/mobilelogin.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename = 'bootstrap/css/bootstrap.min.css')}}">
<div class="container">
<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2022</p>
  </form>
</main>
</div>

{% endblock %}

templates/createcenter.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  

  <link rel="stylesheet" href="{{url_for('static',filename = 'bootstrap/css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename = 'mystyle/mystyle.css')}}">
  <script src="{{url_for('static',filename = 'bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{url_for('static',filename = 'cdnjs/jquery.min.js')}}"></script>
  <link rel="stylesheet" href="{{url_for('static',filename = 'bootstrap/css/bootstrap_table_css.css')}}">

  <script src="{{url_for('static',filename = 'bootstrap/js/bootstrap_table_js.js')}}"></script>
  <script src="{{url_for('static',filename = 'bootstrap/js/bootstrap_table_zn_js.js')}}"></script>
  <script src="{{url_for('static',filename = 'bootstrap/js/bootstrap-table-locale-all.min.js')}}"></script>
  <script src="{{url_for('static',filename = 'richarea/tinymce.min.js')}}"></script>

  <link rel="stylesheet" href="{{url_for('static',filename = 'bootstrap/css/table_icon.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename = 'fontawesome-free-6.4.0-web/css/all.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static',filename = 'animate/animate.css')}}">


</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark base_navbar" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <i class="fa-solid fa-splotch fa-2xl" style="color: #f8f9fc; margin-right:10px"></i>
      <a class="navbar-brand" href="{{ url_for('main') }}">学习助手</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent" >
        <ul class="navbar-nav me-auto mb-2 mb-lg-0" hidden="true">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">学习</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('paper.showanserpaperlist') }}">刷题</a>
          </li>
        </ul>
      </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <button type="button" hidden class="btn btn-light animateclass" style="background: transparent; border:0ch; color: white"
          id='control-panel'>用户界面</button>
        {%if user%}
        <div class="btn-group">
          <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            {{user.username}}
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('users_bp.showusercenter') }}">个人中心</a></li>
          </ul>
        </div>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('logout') }}">注销</a>
        </li>
        {%else%}
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#login">登录</button>
        {%endif%}
      </ul>
    </div>
  </nav>
  
  <main class="d-flex flex-nowrap" >
    
    <div id="leftbar" class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="z-index:9999;position:fixed;height: 100vh;flex-shrink: 0;">
      
      <a href="{{ url_for('show_createcenter') }}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <i class="fa-solid fa-hippo fa-xl"></i>&nbsp &nbsp
        <span class="controlhead">发布中心</span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column mb-auto"  id="ul_header">
        <li class="nav-item">
          <a href="{{ url_for('show_createcenter') }}" class="nav-link  text-white " aria-current="page">
            <i class="fa-solid fa-home"></i>&nbsp
            主页
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for('information.articlelist') }}" class="nav-link  text-white " aria-current="page">
            <i class="fa-solid fa-pencil"></i>&nbsp
            文章管理
          </a>
        </li>
        <li>
          <a href="{{ url_for('paper.showPaperList') }}" class="nav-link text-white">
            <i class="fa-solid fa-person-chalkboard"></i>
            试题管理
          </a>
        </li>
        <li>
          <a href="{{ url_for('paper.unlockuserpaper') }}" class="nav-link text-white">
            <i class="fa-solid fa-hammer"></i>
            试卷补考
          </a>
        </li>
        <li>
          <a href="{{ url_for('manage.insertscore') }}" class="nav-link text-white">
            <i class="fa-solid fa-syringe"></i>
            积分管理
          </a>
        </li>
        <li>
          <a href="#" class="nav-link text-white">
            <i class="fa-solid fa-user"></i>&nbsp
            用户管理
          </a>
        </li>
      </ul>
      <hr>
    </div>
    <div id = "fakecontain" class="d-flex flex-column flex-shrink-0 p-3 "  style=" height:100vh;"></div>
    <div class="d-flex flex-column flex-shrink-0 p-3 " style="height: 100vh;flex-shrink: 0;width:86vw;">
      
      {% block body %}

      {% endblock %}
    </div>
  </main>
</body>
</html>

<script type=text/javascript>
  var ftbar = document.getElementById('leftbar')
  var fakecontain = document.getElementById('fakecontain')
  $('#control-panel').bind('click', function() {
    window.location.href = '/'
  });
  $(document).ready(function () {
    // each 是 为每一个匹配的元素 执行定义的方法
      $("#ul_header").find("a").each(function () {
        // location.pathname 获取 当前浏览器上的url 地址
        if ($(this).attr("href") === location.pathname) {
          $(this).addClass("active");
        } else {
          $(this).removeClass("active");
        }
      });
      fakewidth = ftbar.getBoundingClientRect().width
      fakecontain.style.width=fakewidth+'px'
  });

  $(window).resize(function () {
      fakewidth = ftbar.getBoundingClientRect().width
      fakecontain.style.width=fakewidth+'px'
  });


  

</script>

templates/index.html
{%extends "base.html"%}
{% block body %}
主页
{%endblock %}